-- MySQL Script generated by MySQL Workbench
-- Sun 10 Nov 2019 11:09:06 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libro` ;

CREATE TABLE IF NOT EXISTS `Libro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Coleccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coleccion` ;

CREATE TABLE IF NOT EXISTS `Coleccion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Serie` ;

CREATE TABLE IF NOT EXISTS `Serie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Imprenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Imprenta` ;

CREATE TABLE IF NOT EXISTS `Imprenta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `tipo` ENUM('admin', 'vendedor') NOT NULL DEFAULT 'vendedor',
  `estatus` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Comprador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comprador` ;

CREATE TABLE IF NOT EXISTS `Comprador` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NULL,
  `NoCuenta` VARCHAR(45) NULL DEFAULT 'N/A',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Autor` ;

CREATE TABLE IF NOT EXISTS `Autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NULL,
  `nombreLegal` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `Version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Version` ;

CREATE TABLE IF NOT EXISTS `Version` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Libro_id` INT UNSIGNED NOT NULL,
  `ISBN` VARCHAR(20) NOT NULL,
  `edicion` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `precioLista` DECIMAL(6,2) NOT NULL,
  `reserva` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `fecha` DATE NOT NULL,
  `formato` ENUM('pasta blanda', 'pasta dura', 'digital') NOT NULL DEFAULT 'pasta blanda',
  `portada` VARCHAR(20) NULL DEFAULT 'N/A',
  `nota` TINYTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC),
  INDEX `fk_Version_Libro1_idx` (`Libro_id` ASC),
  CONSTRAINT `fk_Version_Libro1`
    FOREIGN KEY (`Libro_id`)
    REFERENCES `Libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `ImpresionLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ImpresionLibro` ;

CREATE TABLE IF NOT EXISTS `ImpresionLibro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Version_id` INT UNSIGNED NOT NULL,
  `Imprenta_id` INT UNSIGNED NOT NULL,
  `impresion` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `fecha` DATE NOT NULL,
  `ejemplares` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ImpresionLibro_Imprenta1_idx` (`Imprenta_id` ASC),
  INDEX `fk_ImpresionLibro_Version1_idx` (`Version_id` ASC),
  CONSTRAINT `fk_ImpresionLibro_Imprenta1`
    FOREIGN KEY (`Imprenta_id`)
    REFERENCES `Imprenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ImpresionLibro_Version1`
    FOREIGN KEY (`Version_id`)
    REFERENCES `Version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `ColeccionLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ColeccionLibro` ;

CREATE TABLE IF NOT EXISTS `ColeccionLibro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Version_id` INT UNSIGNED NOT NULL,
  `Coleccion_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coleccionLibro_Version1_idx` (`Version_id` ASC),
  INDEX `fk_coleccionLibro_Coleccion1_idx` (`Coleccion_id` ASC),
  CONSTRAINT `fk_coleccionLibro_Version1`
    FOREIGN KEY (`Version_id`)
    REFERENCES `Version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coleccionLibro_Coleccion1`
    FOREIGN KEY (`Coleccion_id`)
    REFERENCES `Coleccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `SerieLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SerieLibro` ;

CREATE TABLE IF NOT EXISTS `SerieLibro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Version_id` INT UNSIGNED NOT NULL,
  `Serie_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_serieLibro_Serie1_idx` (`Serie_id` ASC),
  INDEX `fk_serieLibro_Version1_idx` (`Version_id` ASC),
  CONSTRAINT `fk_serieLibro_Serie1`
    FOREIGN KEY (`Serie_id`)
    REFERENCES `Serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serieLibro_Version1`
    FOREIGN KEY (`Version_id`)
    REFERENCES `Version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `VentasLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VentasLibro` ;

CREATE TABLE IF NOT EXISTS `VentasLibro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Usuario_id` INT UNSIGNED NOT NULL,
  `Comprador_id` INT UNSIGNED NOT NULL,
  `Version_id` INT UNSIGNED NOT NULL,
  `cantidad` SMALLINT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `tipoPrecio` ENUM('precioLista', 'desc1', 'desc2') NOT NULL DEFAULT 'precioLista',
  `precio` DECIMAL(6,2) NOT NULL,
  `recibo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VentasLibro_Usuario1_idx` (`Usuario_id` ASC),
  INDEX `fk_VentasLibro_Comprador1_idx` (`Comprador_id` ASC),
  INDEX `fk_VentasLibro_Version1_idx` (`Version_id` ASC),
  CONSTRAINT `fk_VentasLibro_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentasLibro_Comprador1`
    FOREIGN KEY (`Comprador_id`)
    REFERENCES `Comprador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VentasLibro_Version1`
    FOREIGN KEY (`Version_id`)
    REFERENCES `Version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



-- -----------------------------------------------------
-- Table `AutoriaLibro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AutoriaLibro` ;

CREATE TABLE IF NOT EXISTS `AutoriaLibro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Autor_id` INT NOT NULL,
  `Version_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_AutoriaLibro_Autor1_idx` (`Autor_id` ASC) ,
  INDEX `fk_AutoriaLibro_Version1_idx` (`Version_id` ASC),
  CONSTRAINT `fk_AutoriaLibro_Autor1`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AutoriaLibro_Version1`
    FOREIGN KEY (`Version_id`)
    REFERENCES `Version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
